version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 213810253225.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t demo .
      - echo Docker image built.
  
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag demo:latest 213810253225.dkr.ecr.ap-south-1.amazonaws.com/demo:latest
      - docker push 213810253225.dkr.ecr.ap-south-1.amazonaws.com/demo:latest
      - echo Docker image pushed to ECR.

artifacts:
  files: '**/*'
